### ISSUE TITLE
Todo highlight group is barely readable

### ISSUE THREAD

**Issue by rawcoder** [mhinz/vim-janah#3]
Keywords in Todo highlight group are barely readable.  Example: ![before](https://cloud.githubusercontent.com/assets/2996616/24829313/aa4ecdc0-1c8c-11e7-91c5-acad2fefcad2.png).

The yellow part is too bright.  Although one can guess the words (AFAIK there are only 3: TODO, XXX, FIXME) by their length it would be convenient to have some other color for this.

**Comment by rawcoder** [comment]
Here's something I came up with:
![after](https://cloud.githubusercontent.com/assets/2996616/24829370/b9238d26-1c8d-11e7-8bf9-fc1debf5d005.png)

Diff:
```diff
-highlight Todo guifg=#ffdfaf ctermfg=223 ctermbg=NONE gui=NONE cterm=NONE
+highlight Todo guifg=#0f4f4f guibg=#ffdfaf ctermfg=223 ctermbg=NONE gui=bold cterm=NONE
```

**Comment by mhinz** [comment]
Since you see the yellow, although `ctermbg=NONE`, you're probably using `set termguicolors`. So the actual issue is a missing `guibg=NONE`.

The yellow comes from the default colorscheme. The output of `:colo default | hi Todo` will show `guibg=Yellow`.

Back when I used this colorscheme (I use light colorschemes nowadays), I never used the GUI definitions, so this colorscheme works best without `termguicolors` (that feature didn't even exist back then).

**Comment by mhinz** [comment]
I added a few missing `guibg` definitions, so it should look fine now, no matter what other colorscheme was used before.

Thanks for bringing this up!
